import Head from 'next/head';
import {BsFillMoonStarsFill} from "react-icons/bs"

export default function Home() {
  return (
    <div>
      <Head>
        <title>jia-ayo portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
      <section className="min-h-screen">
        <nav className="py-10 mb-10 flex justify-between">
          <h1 className="text-xl">Developed by JIA</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill/>
            </li>
            <li><a>Resume</a></li>
          </ul>
        </nav>
      </section>
      </main>
    </div>
  )
}
